[Settings]
ID = "tome-gatsby"

[build]
NODE_VERSION = "10.16.3"
YARN_VERSION = "1.17.0"
YARN_FLAGS = "--no-ignore-optional"
command = "cd gatsby && rm -rf node_modules && npm i -g && yarn install && yarn add lovell/sharp && npm rebuild sharp --update-binary && yarn run build"
publish = "gatsby/public"

 
