[Settings]
ID = "tome-gatsby"

[build]
NODE_VERSION = "10.16.3"
YARN_FLAGS = "--no-ignore-optional"
command = "rm -rf node_modules && npm i -g yarn && cd gatsby && npm rebuild sharp --update-binary && yarn install && yarn run build"
publish = "gatsby/public"

 
